import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav className='grid grid-flow-col items-center justify-start gap-4 w-full'>
          <Link  href="/"><button className='flex items-center justify-center p-4 bg-white rounded-xl text-black font-bold '>Home</button> </Link>
          <Link  href="/cie"><button className='flex items-center justify-center p-4 bg-white rounded-xl text-black font-bold '>cie</button> </Link>
        </nav>
      </header>  
      
      <div className="flex min-h-screen flex-col items-center  p-24 w-screen">
        
      <div className={inter.className}>{children}</div>
      </div>
      </body>
      
    </html>
  )
}
